export const convertApplicationsArrayToMap = (snapshot) => {
  try {
    // Adding id to the transformedApplcationArray.
    // The id is the id generated by firestore doc
    const transformedApplicationsArray = snapshot.docs.map((doc) => {
      return {
        ...doc.data(),
        id: doc.id,
      };
    });

    // Convert the array of Objects into map
    return transformedApplicationsArray.reduce((accumulator, appObj) => {
      accumulator[appObj.route] = appObj;
      return accumulator;
    }, {});
  } catch (error) {
    console.log("Error converting appicationsArray to map", error);
  }
};

export const transformAppLogoItemsArray = (snapshot) => {
  try {
    const transformedAppLogoItemsArray = snapshot.docs.map((doc) => {
      return {
        ...doc.data(),
        id: doc.id,
      };
    });

    return transformedAppLogoItemsArray;
  } catch (error) {
    console.log("Error transforming app Logo Items array", error);
  }
};
