const PigGamePlayer2ActionTypes = {
  SIGN_IN_START: "PIGGAME_SIGN_IN_START",
  SIGN_IN_FAILURE: "PIGGAME_SIGN_IN_FAILURE",
  SIGN_IN_SUCCESS: "PIGGAME_SIGN_IN_SUCCESS",
  SIGN_OUT_START: "PIGGAME_SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "PIGGAME_SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "PIGGAME_SIGN_OUT_FAILURE",
  LOAD_PLAYER2_STATE: "PIGGAME_LOAD_PLAYER2_STATE",
  IS_PIGGAME_PLAYER2_LOGGED: "IS_PIGGAME_PLAYER2_LOGGED",
};

export default PigGamePlayer2ActionTypes;
