export const CommentsConverterTypes = {
  INPUT_VIDEOID_ONCHANGE: "INPUT_VIDEOID_ONCHANGE",
  SET_INPUT_VIDEOID: "SET_INPUT_VIDEOID",
  SET_TOSTEP2_SHOW_TRUE: "SET_TOSTEP2_SHOW_TRUE",
  SET_TOSTEP2_SHOW_FALSE: "SET_TOSTEP2_SHOW_FALSE",
};
