const SignUpFormActionTypes = {
    SET_CLICKED_ALERTSVG: "SET_CLICKED_ALERTSVG",
    CLEAR_CLICKED_ALERTSVG: "CLEAR_CLICKED_ALERTSVG",
    SET_IS_SIGNINGUP_TRUE: "SET_IS_SIGNINGUP_TRUE",
    SET_IS_SIGNINGUP_FALSE: "SET_IS_SIGNINGUP_FALSE",
};

export default SignUpFormActionTypes;