const SignInUpActionTypes = {
  SET_RENDER_FOR_SIGNIN: "SET_RENDER_FOR_SIGNIN",
  SET_RENDER_FOR_SIGNIUP: "SET_RENDER_FOR_SIGNIUP",
  SET_RENDER_FOR_REGISTER_SUCCESS: "SET_RENDER_FOR_REGISTER_SUCCESS",
  TOGGLE_SIGNINUP_MODAL: "TOGGLE_SIGNINUP_MODAL",
  TURN_SIGNINUP_OFF: "TURN_SIGNINUP_OFF",
  RESET_SIGNUPFORM_ERROR: "RESET_SIGNUPFORM_ERROR",
  // Sign Up Form
  UPDATE_SIGN_UP_ERROR_OBJ: "UPDATE_SIGN_UP_ERROR_OBJ",
};

export default SignInUpActionTypes;
