const SignInUpActionTypes = {
  SET_RENDER_FOR_SIGNIN: "SET_RENDER_FOR_SIGNIN",
  SET_RENDER_FOR_SIGNIUP: "SET_RENDER_FOR_SIGNIUP",
  SET_RENDER_FOR_REGISTER_SUCCESS: "SET_RENDER_FOR_REGISTER_SUCCESS",
  TOGGLE_SIGNINUP_MODAL: "TOGGLE_SIGNINUP_MODAL",
  TURN_SIGNINUP_OFF: "TURN_SIGNINUP_OFF",
};

export default SignInUpActionTypes;
