const SignInUpActionTypes = {
  SET_RENDER_FOR_SIGNIN: "SET_RENDER_FOR_SIGNIN",
  SET_RENDER_FOR_SIGNIUP: "SET_RENDER_FOR_SIGNIUP",
  SET_RENDER_FOR_REGISTER_SUCCESS: "SET_RENDER_FOR_REGISTER_SUCCESS",
  TOGGLE_SIGNINUP_MODAL: "TOGGLE_SIGNINUP_MODAL",
  TURN_SIGNINUP_OFF: "TURN_SIGNINUP_OFF",
  RESET_SIGNUPFORM_ERROR: "RESET_SIGNUPFORM_ERROR",
  // Sign Up Form
  UPDATE_SIGN_UP_ERROR_OBJ: "UPDATE_SIGN_UP_ERROR_OBJ",
  SET_PROCESSING_SIGNIN_TRUE: "PROCESSING_SIGNIN_TRUE",
  SET_PROCESSING_SIGNIN_FALSE: "PROCESSING_SIGNIN_FALSE",
  EMAIL_ALREADY_IN_USE_TRUE: "EMAIL_ALREADY_IN_USE_TRUE",
  EMAIL_ALREADY_IN_USE_FALSE: "EMAIL_ALREADY_IN_USE_FALSE",
  PASSWORD_INCORRECT_TRUE: "PASSWORD_INCORRECT_TRUE",
  PASSWORD_INCORRECT_FALSE: "PASSWORD_INCORRECT_FALSE",
  EMAIL_NOTREGISTERED_TRUE: "EMAIL_NOTREGISTERED_TRUE",
  EMAIL_NOTREGISTERED_FALSE: "EMAIL_NOTREGISTERED_FALSE",
  RESET_SIGNINFORM_ERROR: "RESET_SIGNINFORM_ERROR",
};

export default SignInUpActionTypes;
