const AuthActionTypes = {
  GOOGLE_AUTHORIZATION_SUCCESS: "GOOGLE_AUTHORIZATION_SUCCESS",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  CHECK_AUTH_SESSION: "CHECK_AUTH_SESSION",
  SIGN_OUT: "SIGN_OUT",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SET_SIGNUP_ALERT: "SET_SIGNUP_ALERT",
  SET_LOGIN_ALERT: "SET_LOGIN_ALERT",
  CLEAR_SIGNUP_ALERT: "CLEAR_SIGNUP_ALERT",
  CLEAR_LOGIN_ALERT: "CLEAR_LOGIN_ALERT",
  SET_ISLOGGED_TRUE: "SET_ISLOGGED_TRUE",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_USER_AVATAR: "SET_USER_AVATAR",
};
export default AuthActionTypes;
