const PigGameActionTypes = {
  CHANGE_DICE_NUM: "CHANGE_DICE_NUM",
  SWITCH_ACTIVE_PLAYER: "SWITCH_ACTIVE_PLAYER",
  PLAYER_ADD_TOTAL_SCORE: "PLAYER_ADD_TOTAL_SCORE",
  PLAYER_CLEAR_TOTAL_SCORE: "PLAYER_CLEAR_TOTAL_SCORE",
  PLAYER_ADD_CURRENT_SCORE: "PLAYER_ADD_CURRENT_SCORE",
  PLAYER_CLEAR_CURRENT_SCORE: "PLAYER_CLEAR_CURRENT_SCORE",
  CHANGE_WINNER: "CHANGE_WINNER",
  START_NEW_GAME: "START_NEW_GAME",
};

export default PigGameActionTypes;
