const PigGameActionTypes = {
  CHANGE_DICE_NUM: "CHANGE_DICE_NUM",
  SWITCH_ACTIVE_PLAYER: "SWITCH_ACTIVE_PLAYER",
  PLAYER_ADD_TOTAL_SCORE: "PLAYER_ADD_TOTAL_SCORE",
  PLAYER_CLEAR_TOTAL_SCORE: "PLAYER_CLEAR_TOTAL_SCORE",
  PLAYER_ADD_CURRENT_SCORE: "PLAYER_ADD_CURRENT_SCORE",
  PLAYER_CLEAR_CURRENT_SCORE: "PLAYER_CLEAR_CURRENT_SCORE",
  CHECK_WINNER: "CHECK_WINNER",
  START_NEW_GAME: "START_NEW_GAME",
  CHANGE_FINAL_SCORE: "CHANGE_FINAL_SCORE",
  CHANGE_PREV_SCORES: "CHANGE_PREV_SCORES",
  LOAD_GAME_STATE: "LOAD_GAME_STATE",
  LOADING_FINISHED: "LOADING_FINISHED",
  SET_ISLOADING_TRUE: "SET_ISLOADING_TRUE",
  RESET_PREV_SCORE: "RESET_PREV_SCORE",
};

export default PigGameActionTypes;
