const ShopActionTypes = {
  FETCH_APPLICATIONS_START: "FETCH_APPLICATIONS_START",
  FETCH_APPLICATIONS_SUCCESS: "FETCH_APPLICATIONS_SUCCESS",
  FETCH_APPLICATIONS_FAILURE: "FETCH_APPLICATIONS_FAILURE",
};

export default ShopActionTypes;
