const LogINFormActionTypes = {
  SET_CLICKED_ALERTSVG_LOGIN: "SET_CLICKED_ALERTSVG_LOGIN",
  CLEAR_CLICKED_ALERTSVG_LOGIN: "CLEAR_CLICKED_ALERTSVG_LOGIN",
  SET_IS_LOGGINGIN_TRUE: "SET_IS_LOGGINGIN_TRUE",
  SET_IS_LOGGINGIN_FALSE: "SET_IS_LOGGINGIN_FALSE",
};

export default LogINFormActionTypes;
