import firebase from "firebase/app";
import "firebase/firestore";
import "firebase/auth";

const config = {
  apiKey: "AIzaSyAtmhKbajvfftAY34PKVsMUfCglDxQCZBQ",
  authDomain: "ourdailyapp.firebaseapp.com",
  databaseURL: "https://ourdailyapp.firebaseio.com",
  projectId: "ourdailyapp",
  storageBucket: "ourdailyapp.appspot.com",
  messagingSenderId: "802609740539",
  appId: "1:802609740539:web:ad5066d9ce22714a10ce5e",
  measurementId: "G-XKBNYDPQ1F",
};
// Initialize Firebase
firebase.initializeApp(config);

export const auth = firebase.auth();
export const firestore = firebase.firestore();

// Google Authentication
const provider = new firebase.auth.GoogleAuthProvider();
provider.setCustomParameters({ prompt: "select_account" });
export const signInWithGoogle = () => auth.signInWithPopup(provider);

// =============== Custom functions =================

//===== firestore =====
export const addCollectionAndDocuments = (collectionName, objToAdd) => {
  try {
    const collectionRef = firestore.collection(collectionName);

    const batch = firestore.batch();

    objToAdd.forEach((obj) => {
      const newDocRef = collectionRef.doc();
      batch.set(newDocRef, obj);
    });

    batch.commit();
  } catch (error) {
    console.log("Error adding collection and documents", error);
  }
};

export const convertApplicationsArrayToMap = (snapshot) => {
  try {
    // Adding id to the transformedApplcationArray.
    // The id is the id generated by firestore doc
    const transformedApplicationsArray = snapshot.docs.map((doc) => {
      return {
        ...doc.data(),
        id: doc.id,
      };
    });

    // Convert the array of Objects into map
    return transformedApplicationsArray.reduce((accumulator, appObj) => {
      accumulator[appObj.route] = appObj;
      return accumulator;
    }, {});
  } catch (error) {
    console.log("Error converting appicationsArray to map", error);
  }
};

//===== User =====
export const createUserProfileDocument = async (user, additionalData) => {
  if (!user) {
    return;
  }

  const userRef = firestore.doc(`user/${user.uid}`);

  const userSnapShot = await userRef.get();
  // console.log(user);
  if (!userSnapShot.exists) {
    const { displayName, photoURL, email } = user;

    const createdAt = new Date();

    try {
      await userRef.set({
        //In Google Log In Auth
        displayName,
        photoURL,
        email,
        createdAt,
        //From email password form
        ...additionalData,
      });
    } catch (error) {
      console.log(`error creating user`, error.message);
    }
  }

  return userRef;
};

export default firebase;
