const UserActionTypes = {
  SET_USER: "SET_USER",
  USER_LOGGED_ON: "USER_LOGGED_ON",
  USER_LOGGED_OFF: "SER_LOGGED_OFF",
  GOOGLE_SIGN_IN: "GOOGLE_SIGN_IN",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
};
export default UserActionTypes;
