const UserActionTypes = {
  SET_USER: "SET_USER",
  USER_LOGGED_ON: "USER_LOGGED_ON",
  USER_LOGGED_OFF: "SER_LOGGED_OFF",
  GOOGLE_SIGN_IN: "GOOGLE_SIGN_IN",
  EMAIL_SIGN_IN: "EMAIL_SIGN_IN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_START: "SIGN_OUT_START",
  SING_OUT_SUCCESS: "SING_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
};
export default UserActionTypes;
