const CartActionTypes = {
  ADD_ITEM_CART: "ADD_ITEM_CART",
  GET_CART_APPS_START: "GET_CART_APPS_START",
  GET_CART_APPS_SUCCESS: "GET_CART_APPS_SUCCESS",
  GET_CART_APPS_FAILURE: "GET_CART_APPS_FAILURE",
  REMOVE_APP_FROM_CART_START: "REMOVE_APP_FROM_CART_START",
  SET_GETTING_CART_APPS_TRUE: "SET_GETTING_CART_APPS_TRUE",
  SET_GETTING_CART_APPS_FALSE: "SET_GETTING_CART_APPS_FALSE",
  POPULATE_CART_APPS: "POPULATE_CART_APPS",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  CLEAR_CART: "CLEAN_CART",
  TOGGLE_CART_POPUP_HIDDEN: "TOGGLE_CART_POPUP_HIDDEN",
  CLOSE_CART_POPUP: "CLOSE_CART_POPUP",
  ADD_ITEM_PRICE: "ADD_ITEM_PRICE",
  MINUS_ITEM_PRICE: "MINUS_ITEM_PRICE",
  MOVE_TO_WISHLIST: "MOVE_TO_WISHLIST",
  ADD_APP_START: "ADD_APP_START",
  ADD_APP_SUCCESS: "ADD_APP_SUCCESS",
  ADD_APP_FAILURE: "ADD_APP_FAILURE",
  //==================== Wish list item ==================
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  REMOVE_ITEM_WISHLIST: "REMOVE_ITEM_WISHLIST",
  TOGGLE_ITEM_WISHLIST: "TOGGLE_ITEM_WISHLIST",
  MOVE_TO_CARTLIST: "MOVE_TO_CARTLIST",
};

export default CartActionTypes;
