const CartActionTypes = {
  ADD_ITEM_CART: "ADD_ITEM_CART",
  REMOVE_ITEM_CART: "REMOVE_ITEM_CART",
  CLEAR_CART: "CLEAN_CART",
  TOGGLE_CART_POPUP_HIDDEN: "TOGGLE_CART_POPUP_HIDDEN",
  ADD_ITEM_PRICE: "ADD_ITEM_PRICE",
  MINUS_ITEM_PRICE: "MINUS_ITEM_PRICE",
  MOVE_TO_WISHLIST: "MOVE_TO_WISHLIST",
  //==================== Wish list item ==================
  ADD_ITEM_WISHLIST: "ADD_ITEM_WISHLIST",
  REMOVE_ITEM_WISHLIST: "REMOVE_ITEM_WISHLIST",
  MOVE_TO_CARTLIST: "MOVE_TO_CARTLIST",
};

export default CartActionTypes;
