const UserActionTypes = {
    IS_UPLOADING_AVATAR_TRUE: "IS_UPLOADING_AVATAR_TRUE",
    IS_UPLOADING_AVATAR_FALSE: "IS_UPLOADING_AVATAR_FALSE",
    IS_UPDATING_USER_DETAILS_TRUE: "IS_UPDATING_USER_DETAILS_TRUE",
    IS_UPDATING_USER_DETAILS_FALSE: "IS_UPDATING_USER_DETAILS_FALSE",
    UPDATE_USER_DETAILS_START: "UPDATE_USER_DETAILS_START",
    UPDATE_USER_DETAILS_SUCCESS: "UPDATE_USER_DETAILS_SUCCESS",
    UPDATE_USER_DETAILS_FAILURE: "UPDATE_USER_DETAILS_FAILURE",
    UPDATE_USER_AVATAR_START: "UPDATE_USER_AVATAR_START",
    UPDATE_USER_AVATAR_SUCCESS: "UPDATE_USER_AVATAR_SUCCESS",
    UPDATE_USER_AVATAR_FAILURE: "UPDATE_USER_AVATAR_FAILURE",
}

export default UserActionTypes;