const PigGameModalsActionTypes = {
  TOGGLE_SIGNIN_MODAL: "TOGGLE_SIGNIN_MODAL",
  TURN_SIGNIN_OFF: "TURN_SIGNIN_OFF",
  PASSWORD_INCORRECT_TRUE: "PASSWORD_INCORRECT_TRUE",
  PASSWORD_INCORRECT_FALSE: "PASSWORD_INCORRECT_FALSE",
  EMAIL_NOTREGISTERED_TRUE: "EMAIL_NOTREGISTERED_TRUE",
  EMAIL_NOTREGISTERED_FALSE: "EMAIL_NOTREGISTERED_FALSE",
  RESET_SIGNIN_ERROR: "RESET_SIGNIN_ERROR",
  SET_PROCESSING_SIGNIN_TRUE: "PROCESSING_SIGNIN_TRUE",
  SET_PROCESSING_SIGNIN_FALSE: "PROCESSING_SIGNIN_FALSE",
};

export default PigGameModalsActionTypes;
