const PigGameModalsActionTypes = {
  TOGGLE_SIGNIN_MODAL: "TOGGLE_SIGNIN_MODAL",
  TURN_SIGNIN_OFF: "TURN_SIGNIN_OFF",
  TOGGLE_INFO_MODAL: "TOGGLE_INFO_MODAL",
  TURN_INFO_MODAL_OFF: "TURN_INFO_MODAL_OFF",
  PASSWORD_INCORRECT_TRUE: "PIGGAME_PLAYER2_PASSWORD_INCORRECT_TRUE",
  PASSWORD_INCORRECT_FALSE: "PIGGAME_PLAYER2_PASSWORD_INCORRECT_FALSE",
  EMAIL_NOTREGISTERED_TRUE: "PIGGAME_PLAYER2_EMAIL_NOTREGISTERED_TRUE",
  EMAIL_NOTREGISTERED_FALSE: "PIGGAME_PLAYER2_EMAIL_NOTREGISTERED_FALSE",
  RESET_SIGNIN_ERROR: "RESET_SIGNIN_ERROR",
  SET_PROCESSING_SIGNIN_TRUE: "PROCESSING_SIGNIN_TRUE",
  SET_PROCESSING_SIGNIN_FALSE: "PROCESSING_SIGNIN_FALSE",
  SIGNINFORM_ONHIDE: "PIGGAME_PLAYER2_SIGNINFORM_ONHIDE",
};

export default PigGameModalsActionTypes;
